### ISSUE TITLE
Feature requirement for showing the positive or negative correlation in the plot

### ISSUE THREAD

**Issue by B-1991-ing** [Hy4m/linkET#12]
Hi Houyun,

Could you add one feature requirement to show the **negative** correlation using the **dotted** curves and the **positive** correlation using the **solid** curves? Then it will be easier for people to directly see the negative or positive correlation between two matrixes.

For now, all my correlated curves are solid.
![image](https://user-images.githubusercontent.com/54441633/224994076-78915747-cc7c-45ac-a853-b443e727221f.png)

Best,

Bing

**Comment by Hy4m** [comment]
you can

set `linetype = 'dashed'` parameter in `geom_couple()` layer function.

**Comment by B-1991-ing** [comment]
Is there a way to set the **negative** Mantel's r with **dashed** lines and **positive** Mantel's r with **solid** lines?
If directly set the livetype = "dashed", all lines will be dashed.

![image](https://user-images.githubusercontent.com/54441633/228888731-43c9b51e-c927-4427-af97-c9913d53a542.png)

**Comment by B-1991-ing** [comment]
I also want to know the **positive or negative** relationship between the matrixes.

**Comment by B-1991-ing** [comment]
<img width="747" alt="Screenshot 2023-04-01 at 09 37 34" src="https://user-images.githubusercontent.com/54441633/229272603-39ce0205-9cb2-4515-8294-4cd70d15589d.png">

Hi Houyun,

Is it difficult to add the feature of the solid and dashed lines to make a difference between the positive or negative mantel test relationships, as shown above?

Best,

Bing

**Comment by Hy4m** [comment]
This part is the same as pure `ggplot2`, you need to map the `linetype` to mantel's r and then adjust it using `scale_linetype_manual()`.

Here's an example:

```r
library(linkET)
library(ggplot2)
library(dplyr)
data("varechem", package = "vegan")
data("varespec", package = "vegan")

mantel <- mantel_test(varespec, varechem,
                      spec_select = list(Spec01 = 1:7,
                                         Spec02 = 8:18,
                                         Spec03 = 19:37,
                                         Spec04 = 38:44)) %>% 
  mutate(rd = cut(r, breaks = c(-Inf, 0.2, 0.4, Inf),
                  labels = c("< 0.2", "0.2 - 0.4", ">= 0.4")),
         pd = cut(p, breaks = c(-Inf, 0.01, 0.05, Inf),
                  labels = c("< 0.01", "0.01 - 0.05", ">= 0.05")))

qcorrplot(correlate(varechem), type = "lower", diag = FALSE) +
  geom_square() +
  geom_couple(aes(colour = pd, size = rd, linetype = r > 0), 
              data = mantel, 
              curvature = nice_curvature()) +
  scale_fill_gradientn(colours = RColorBrewer::brewer.pal(11, "RdBu")) +
  scale_size_manual(values = c(0.5, 1, 2)) +
  scale_colour_manual(values = color_pal(3)) +
  scale_linetype_manual(values = c("TRUE" = "solid", "FALSE" = "dashed")) +
  guides(size = guide_legend(title = "Mantel's r",
                             override.aes = list(colour = "grey35"), 
                             order = 2),
         colour = guide_legend(title = "Mantel's p", 
                               override.aes = list(size = 3), 
                               order = 1),
         fill = guide_colorbar(title = "Pearson's r", order = 3))
```

**Comment by B-1991-ing** [comment]
<img width="409" alt="Screenshot 2023-04-02 at 11 48 39" src="https://user-images.githubusercontent.com/54441633/229345391-61d75f83-50f7-41f1-b511-fd10ab58df89.png">

![image](https://user-images.githubusercontent.com/54441633/229345780-59ab2442-ca37-4fc5-a649-80d8aeea37b1.png)

Yeah, thank you Houyun. I also added the code on making my own plots. But, in both figures, why **all significant Mantel's r** are **positive related lines** and only some **non-significant Mantel's r** represent **negative relationship**? Is it a bit strange?

Best,

Bing

**Comment by Hy4m** [comment]
Whether the result is reasonable or not requires professional knowledge to judge.😂
