### ISSUE TITLE
Multiple results for CFLAGS found, something is wrong.FALSE

### ISSUE THREAD

**Issue by TottiD** [Hy4m/linkET#14]
从Github安装失败：错误: Failed to install 'linkET' from GitHub:
      Multiple results for CFLAGS found, something is wrong.FALSE
以下是我的版本信息：
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          2.3                         
year           2023                        
month          03                          
day            15                          
svn rev        83980                       
language       R                           
version.string R version 4.2.3 (2023-03-15)
nickname       Shortstop Beagle 

我从您的GitHub库也没找到tar.gz源文件，请问您这怎么解决？

**Comment by Hy4m** [comment]
直接用从GitHub安装试试：

```
devtools::install_github("Hy4m/linkET", force = TRUE)
```

**Comment by TottiD** [comment]
谢谢您，这边我把您的github库重新打包再安装就成功了！谢谢您
