### ISSUE TITLE
How to fill the missed values in matrix before running linkET?

### ISSUE THREAD

**Issue by B-1991-ing** [Hy4m/linkET#18]
Hi Houyun,

How do you usually do when your matrix have some missed values? If I don't fill the missed values, I will have error when using the linkET.

**Matrix**
[matrix.txt](https://github.com/Hy4m/linkET/files/11428363/matrix.txt)

Thank you very much.

Best,

Bing

**Comment by Hy4m** [comment]
Compute correlation or others?

**Comment by Hy4m** [comment]
> For mantel_test and qcorrplot(correlate()).
> […](#)

Maybe the `use` argument in the `correlate` function can solve your problem😂

**Comment by B-1991-ing** [comment]
What kind of argument in the correlate function?


I actually want to do the same figure as what i sent youu last time. But, this time, I have some missed values in the first matrix.


So, how do you usually deal with this kind of incomplete matrix?


Best,


Bing

________________________________

**Comment by Hy4m** [comment]
> What kind of argument in the correlate function? I actually want to do the same figure as what i sent youu last time. But, this time, I have some missed values in the first matrix. So, how do you usually deal with this kind of incomplete matrix? Best, Bing
> […](#)

The following example should solve your problem. However, there may be some errors when you run it, because there are bugs in the previous version, which can only be completely solved after I push the new version tomorrow.

```r
## replace some data with NA
varespec[sample(nrow(varespec), 3), sample(ncol(varespec), 2)] <- NA
varechem[sample(nrow(varechem), 3), sample(ncol(varechem), 2)] <- NA

library(linkET)

set_corrplot_style()
qcorrplot(correlate(varechem, use = "pairwise.complete.obs")) +
  geom_square()

mantel_test(varespec, varechem)
```

**Comment by B-1991-ing** [comment]
Thank you very much.


Tomorrow is okay.


But, could you explain me a bit about the process of replacing NA in matrix tomorrow? By mean value, random forest or other algorithms?


Have a nice evening.


Best,


Bing

________________________________

**Comment by B-1991-ing** [comment]
Hi Houyun,

In your code, 

**## replace some data with NA
varespec[sample(nrow(varespec), 3), sample(ncol(varespec), 2)] <- NA
varechem[sample(nrow(varechem), 3), sample(ncol(varechem), 2)] <- NA

library(linkET)

set_corrplot_style()
qcorrplot(correlate(varechem, use = "pairwise.complete.obs")) +
  geom_square()

mantel_test(varespec, varechem)**

Did you **ignore the rows with the NA values** or **your code replaces the  the NA values in the matrix as 0 or other automatic values**?

Best,

Bing
