### ISSUE TITLE
关于geom_square函数设定数据范围的问题

### ISSUE THREAD

**Issue by feather-W** [Hy4m/linkET#20]
您好，我在绘制mantel test相关性热图的时候没有展示对角线上的相关性数据，但是这让我的相关性热图的方块都很小。我的相关性热图的相关性系数范围时-0.2到0.2（排除了对角线上的相关系数），现在我想将geom_square的范围调到-0.2到0.2之间，我应该怎么做呢？

**Comment by Hy4m** [comment]
@feather-W 目前可能没有很好的办法，而且我也不建议缩放R的区间。推荐你把geom_square()换成geom_tile()

**Comment by feather-W** [comment]
> @feather-W 目前可能没有很好的办法，而且我也不建议缩放R的区间。推荐你把geom_square()换成geom_tile()

好的，谢谢您的回复！
祝好
