### ISSUE TITLE
Data volume

### ISSUE THREAD

**Issue by jiaxinwang123456** [Hy4m/linkET#23]
Hello, I would like to inquire if the linkET package can run a data volume of over 20000 lines?

**Comment by Hy4m** [comment]
compute correlation using `correlate()` function?

**Comment by jiaxinwang123456** [comment]
I want to use R to calculate the mantel_test test, and there are 20000 rows of data. After importing R language, there were no errors but no graphs were generated, so I want to ask if mantel_test can't calculate so much data?

**Comment by Hy4m** [comment]
> I want to use R to calculate the mantel_test test, and there are 20000 rows of data. After importing R language, there were no errors but no graphs were generated, so I want to ask if mantel_test can't calculate so much data?

Firstly, you should comfirm that all variables (OTUs) are on columns. And then, you can set `mantel_fun` argument to `"mantel.randtest"`, this means using `ade4` package to compute mantel test.

**Comment by jiaxinwang123456** [comment]
I got it, thank you!
