### ISSUE TITLE
Error in cor(as.vector(xdis), ydis, method = method, use = use) :    missing observations in cov/cor

### ISSUE THREAD

**Issue by B-1991-ing** [Hy4m/linkET#6]
Hi Houyun,

I am using the linkET to see the correlation between two matrixes, error always happened in the Rstudio.

**Error screenshot**
<img width="549" alt="Screenshot 2022-11-05 at 12 50 48" src="https://user-images.githubusercontent.com/54441633/200118462-e57c7de2-2689-4f49-b5da-3cf2a4ae8fa4.png">

**The code**
[linkET_Sib_amo_cox_code.pdf](https://github.com/Hy4m/linkET/files/9943732/linkET_Sib_amo_cox_code.pdf)

**The excel table**
[omstrup33_sillebotten_mam copy.xlsx](https://github.com/Hy4m/linkET/files/9943728/omstrup33_sillebotten_mam.copy.xlsx)

Do you have any idea why it always occcurs?

Best,

Bing

**Comment by B-1991-ing** [comment]
Hi Houyun,

**Update**

I noticed that when the table has the number value as "0", the error warning appeared.

**Table screenshot**
<img width="636" alt="Screenshot 2022-11-05 at 17 53 15" src="https://user-images.githubusercontent.com/54441633/200131882-0646d956-0a7d-46b9-a7a5-f0d9f5d5c2da.png">

**Error screenshot**
<img width="464" alt="Screenshot 2022-11-05 at 17 54 12" src="https://user-images.githubusercontent.com/54441633/200131914-e364d0dd-37d8-4fd2-b833-f3af7ccb1546.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
If I have a matrix with the first whole column of 0 in the matrix. Should I directly delete it from the data frame?

**Data frame screenshot**
<img width="802" alt="Screenshot 2022-11-05 at 23 37 20" src="https://user-images.githubusercontent.com/54441633/200143926-d04adaca-2aee-4265-b7c1-932a70ac6571.png">


Best,

Bing

**Comment by Hy4m** [comment]
Hi Bing

I think this happens because the default distance method of spec is bray, but for the bray distance method, the row sum of the data (for each selected group) cannot be 0. So, you can solve this problem by setting the parameter spec_dist = dist_func(.FUN = "vegdist", method = "euclidean").

```
library(linkET)
set.seed(123)
spec <- data.frame(x = sample(0:2, 100, TRUE), y = sample(0:2, 100, TRUE))
env <- data.frame(x = rnorm(100), y = rnorm(100))

## Error: Reproduce your question
mantel_test(spec, env)
## OK
mantel_test(spec, env, spec_dist = dist_func(.FUN = "vegdist", method = "euclidean"))
```

**Comment by Hy4m** [comment]
> Hi Bing
> 
> I think this happens because the default distance method of spec is bray, but for the bray distance method, the row sum of the data (for each selected group) cannot be 0. So, you can solve this problem by setting the parameter spec_dist = dist_func(.FUN = "vegdist", method = "euclidean").
> 
> ```
> library(linkET)
> set.seed(123)
> spec <- data.frame(x = sample(0:2, 100, TRUE), y = sample(0:2, 100, TRUE))
> env <- data.frame(x = rnorm(100), y = rnorm(100))
> 
> ## Error: Reproduce your question
> mantel_test(spec, env)
> ## OK
> mantel_test(spec, env, spec_dist = dist_func(.FUN = "vegdist", method = "euclidean"))
> ```

In the next update, I'll be more careful with spec's default distance algorithm.
