### ISSUE TITLE
How to deal with the dataframe with NA?

### ISSUE THREAD

**Issue by B-1991-ing** [Hy4m/linkET#9]
Hi Houyun,

I want to see the correlation between two dataframe using linkET, but one dataframe has **missing values - NA**.

**Should I move out the rows with NA? Or replace the NA using 0?** 
What I am doing now is to replace the NA with 0, but not sure if it is right.

Could you give me some suggestions?

Best,

Bing

**Comment by Hy4m** [comment]
In my opinion, replacing the missing value with 0 is not appropriate because there are many other situations that can produce a missing value.

In the end, I don't think this is a good place to talk about it, so maybe you could ask it on stackoverflow or some similar forum.
